---
- name: Install Jenkins
  hosts: all
  remote_user: ec2-user
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  become: true

  tasks:
    - name: Download Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Yum update
      yum:
        name: "*"
        state: latest

    - name: Install Java
      dnf:
        name: java-11-amazon-corretto
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: daemon-reload
      systemd:
        daemon-reload: yes

    - name: Systemd enable jenkins
      systemd:
        name: jenkins
        state: started
